language: java
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
jobs:
  include:
  - stage: javadoc
    before_script:
    - source .git_java_doc_functions.sh
    script:
    - "setup_git"
    - "pull_git"
    - "./gradlew assemble"
    - "./gradlew generateJavadoc"
    - "commit_website_files"
    - "upload_files"
env:
  - secure: ZAvEPEYB5ucACd/w0hg41S6EE/mXBXSmsdLiyJ6hubeCWjY0i8dKyMVz65sJo42IFpPEZ59xSolMt76fuUcOWblY22jfHsZsf+AjuuEYX2jvuxRJ29AmGwnjgnJa/xWTIilA0u6mS0880ihwWp7QTqRbroZ7ZkOcNE5K2QWf/CUreluNGFKVl1Gu6iXmGkEnzQRdYfi83Ib3WnpBfAeBUhAFpqKk34vw/JWUoHxAGjyDxyfqZLw8OBnYoC/KCWt2wCCL6mGJN2w9Q/cMRdjQAuPeJ1N2qzhNce4t/aJc2iwewHK1TqYi+FEU2HzJAb+NxxPhqcZv8PQ3XkOb7zK8J3SwzRGe4cYs6GEMqP45rsT38EylfnoKviiUZthA8s3XaI7DjF5cZUKXjrXpRIxR1/q9iM6svArMRCPNZfpz+JW3rhq6HdR5w9/pVGz9qPeNGlDO0TnVoWL+lA0WttASLiD8LOpO1svpYXBKAvXmXqWLE4cPyzCZhTOsxwGDCtyBSZXs7tkApXojiiRtG347VuY9OWEc8yilslvxk77v6od+UYnmENw3AvIrz/uQlRHFFqSrteG5EFkRJyYmGYeO+hH4jFqc6u/GKh5UE5CdpssHBBaoFvCKhMSzXdsnS+P0DnnNeieunGTBtzkmt1U9y9dzFzxdi8eYIaO3kZJT1ks=
